impermanence.nix

This new module have the same usage as the NixOS module but it touches
files and create directories where needed and then use bind mounts
instead of symlinks to access the files.
This is a first step to matching the ideas in #1, but I would like to have the users bit as well further on.
But I still this stand alone can be worth it to begin with if you want to have bind mounts instead.
My local usage:
```nix
{
environment.impermanence."/persistent" = {
directories = [
"/etc/nixos"
"/etc/NetworkManager/system-connections"
];
files = [
"/etc/machine-id"
"/etc/ssh/ssh_host_rsa_key"
"/etc/ssh/ssh_host_rsa_key.pub"
"/etc/ssh/ssh_host_ed25519_key"
"/etc/ssh/ssh_host_ed25519_key.pub"
];
};
}
```
This gives me the following in `/etc/fstab`:
```
/persistent/etc/NetworkManager/system-connections …
```

Add environment.impermanence

---

nixos.nix

This is yet another step towards #1.
With this the full directory structure is replicated with the correct permissions, thus allowing for non-root files and dirs to be bind-mounted. This enforces that the directories and files in the ephemeral storage have exactly matching ownership to their persistent storage correspondents.
I've tested this locally and have managed to bind mount things in my homedir without major issues.
It increases our bash complexity a little bit, but I tried to make the code well documented.

nixos: bind mount with correct permissions

---

nixos.nix

Only assert that persistent paths are marked neededForBoot if they're
file system roots.
Fixes #12

nixos: Only check file systems for neededForBoot

---

README.org
home-manager.nix
lib.nix

Use `bindfs` to create bind mounts for directories instead of symlinking them. This should be less problematic for many applications, since bind mounts are much more transparent.
One service per bind mount is created to keep track of it. In addition, a bind mount is briefly created in the activation script, before `home-manager` switches to the new profile generation, and torn down again at the end of the activation script. This is done to ensure that the links `home-manager` creates end up in the right place; the user services aren't started until either the end of the activation script or the user session begins, and then it's too late.

home-manager: Bind mount directories instead of symlinking them

---

.github/workflows/ci.yml
create-directories.bash
nixos.nix

Extract the `createDirectories` script out into its own file and add CI checks. Also, run the script for directories of files in persistent storage, not just pure directories.

Create directories file

---

create-directories.bash

If there were multiple levels of directories which hadn't yet been created in persistent storage, the `create-directories.bash` script would error out when running `realpath` on the path. To allow this, `realpath` has to be run with `-m`.
Fixes #34

nixos: Fix `No such file or directory` errors on fresh installs

---

README.org
home-manager.nix

Due to what is likely a bug in `bindfs` or `fuse`, the target path is sometimes missing from the mount entry. This causes false positives for the target directory having changed, leading to unnecessary remounts. Luckily, it seems that when this happens, the line instead contains the string `bindfs`, which it doesn't normally, so we can at least circumvent this issue to some degree.
Also, find the correct name of the activation script entry responsible for reloading systemd user services. The name was initially `reloadSystemD` but has been changed to `reloadSystemd`, causing failures due to the unmounts being done after the systemd services are reloaded.
Fixes #36

Fix bindfs unmounts and remounts

---

README.org
home-manager.nix

NixOS defaults to not letting fuse mounts be allowed to let other users read their contents. `bindfs` wants to give other users access and is therefore normally run with `--no-allow-other` to not throw an error.
Giving other users, mainly `root`, access to the bind mounts is, however, useful and works fine when
```nix
{
programs.fuse.userAllowOther = true;
}
```
is declared in `configuration.nix`. This adds an option to choose whether to give other users access or not. It also prompts the user to set the `allowOther` attribute with a link to the documentation.
Should be merged after #38.
Fixes #35

home-manager: Add `allowOther` option to let other users read bind mounts

---

.github/workflows/ci.yml

Since the release of Nix 2.4, the ci pipeline is broken, as the syntax and behavior of `nix run` changed. The command is also considered experimental. Switch to using `nix-shell` instead.

ci: Use nix-shell instead of nix run

---

home-manager.nix

Right now the shell script wrapper doesn't exit which results in a lot of unnecessary bash processes.

home-manager: Use bash exec when calling bindfs

---

README.org
nixos.nix

Manage files by creating a systemd oneshot service for each file. The service links or bind mounts the file as appropriate on start and removes the link or unmounts it when stopped. Whether a symlink or bind mount is used is determined by if the target exists - if it does, it's bind mounted, otherwise symlinked. To make sure files are available early enough, also run the start portion in the activation script.
This lifts the restriction on files being placed in `/etc` and should finally close #1.

nixos: Manage files using systemd services

---

flake.nix

`home-manager.nix` wasn't being added to `nixosModules` on `flake.nix`.
Added it as `impermanence-home`.

Added home manager module to flake.nix

---

home-manager.nix

Make sure the bind mount units start as early as possible in the user session. This should hopefully make issues like #60 less prevalent.

home-manager: Start the bind units as early as possible

---

home-manager.nix

home-manager: Fix unquoted path when creating directories

---

README.org
create-directories.bash
lib.nix
nixos.nix

An overhaul of the current NixOS module which adds a `users` feature, makes the module more extensible, adds permissions handling, and asserts that no duplicates are specified:
Allow user files and directories to be specified as follows:
```nix
{
environment.persistence."/persistent" = {
users.talyz = {
files = [
".screenrc"
];
directories = [
"Downloads"
];
};
};
}
```
This provides an alternative to the home-manager module and may even deprecate it in the future.
Implement support for a submodule representation for files and directories. Strings are automatically converted to appropriate submodule representations and each file and directory is handled based only on their respective submodule's attributes. This means that for most files, a string will suffice, but if more advanced …

nixos: Refactor and implement support for user files + directories

---

home-manager.nix
nixos.nix

The `utillinux` package has been renamed to `util-linux` in `nixpkgs`, causing
our modules to fail to evaluate on `allowAliases = false` configurations.
This just makes us use the "new" name of `util-linux`.

refactor: utillinux -> util-linux

---

nixos.nix

Fixes an issue from #70 where system configs won't eval if no
`environment.persist` confg exists.
~I think this fix is a little hacky, there's probably a better/clear way of
handling this.~ Thought of a better way.

fix(nixos): allow eval to succeed when the module is unused

---

create-directories.bash

Paths are currently split on bash's default delimiters (space, tab and newline) with slashes converted to space. This means paths containing any such delimiters are incorrectly handled, as @etu reported here: https://github.com/nix-community/impermanence/issues/74#issuecomment-1027643883.
Fix this by temporarily replacing bash's default delimiters with `/`, making sure this is the only character we split on.

nixos: Fix the path splitting in create-directories.bash

---

README.org
nixos.nix

This is done by exposing an option `hideMounts` to set the `x-gvfs-hide` mount option on all the bind mounts
Fixes #64

feat(nixos): Support Hiding of Bind Mounts

---

create-directories.bash
mount-file.bash
nixos.nix

This is done to reduce the risk of build errors, isolate each run of the script and reduce the amount of replicated code.
- Make the file mount script generated by `mkMountScript` a discrete script and only generate its invocations.
- Wrap the script invocations in scripts.
Fixes #77, #78
This should let users provide detailed traces of script errors.
In addition to the currently set bash options, set `noglob` and `inherit_errexit`.
- `noglob` disables filename expansion, which could happen in the for loop where we do path splitting if the path contains characters recognized by bash as wildcards, such as `?` or `*`.
- `inherit_errexit` makes subshells inherit the status of the `errexit` option.

nixos: Minimize activation script debug, add debugging, and more

---

README.org
home-manager.nix

Hello, all! A huge thanks to the maintainers :), I've been using impermanence for a while and really love it.
---
As mentioned in https://github.com/nix-community/impermanence/issues/42, bindfs causes some issues with a few specific programs (steam, for example). I'm aware that we have options for using the NixOS module to avoid bindfs, but that may not be preferred (or possible) for some.
This PR allows for setting a specific `method` for each individual directory. They can (atm) be either "bindfs" (the default if not specified) or "symlink".
I've reused the code that links files, but now it runs on `directories` that have `method = "symlink"` as well.
I made sure that changing between the two methods works reliably. For that end, I've added:
- a `cleanEmptyLinkTargets` activation script …

home-manager: adds configurable symlink/bindfs option

---

nixos.nix

When cross-compiling, `patchShebangs` requires the host platform's bash
to be present in the HOST_PATH environment variable. However, when
using `pkgs.runCommand`, only the build platform's bash is added to the
PATH. The result is that the shebang is not replaced, and the script
fails to run because the activation scripts don't have `bash` in their
environment.
Using an explicit `mkDerivation` lets us add the host bash as a
`buildInput`, which makes `patchShebangs` work as expected.
For context, I'm using impermanence on a Raspberry Pi 0. Since no
binary cache exists for that platform, I cross-compile the entire OS and
configuration from an x86_64 host and only push the resulting closure.

Make bash scripts work in cross-compiled environments.

---

mount-file.bash

Tested quickly on NixOS only with [this](https://github.com/ckiee/nixfiles/blob/f4b4002bd53070c625f11b49e1ad23a078c55ee9/modules/imperm.nix) config. 
Seems to work fine I think; for some reason the service output only sometimes got in my deploy log.

mount-file.bash: be quieter when debugging is off

---

nixos.nix

nixos: Mount binds after the persistent storage path

---

README.org
nixos.nix

The `/var/lib/nixos` directory contains the uid and gid map for entities without a static id. Not persisting them means your user and group ids could change between reboots, which is likely undesirable.

nixos: Recommend persisting /var/lib/nixos

---

README.org
create-directories.bash
home-manager.nix
lib.nix
nixos.nix

Construct directory items for all parent directories of the user specified files and directories, assigning better default permissions
and ownership to each and removing this responsibility from the create-directories script.
This means that all parent directories of root directories will now have the default permissions and ownership, not inherit them from the child. User directories are assigned default user ownership. The home directory itself is handled specially to make sure it is owned by the user, not readable by anyone else and its parent gets default root ownership.
To illustrate this with an example, here is a directory specification and the ownership and permissions that could potentially be assigned to the parent directories, given none of them yet exist in persistent storage: …

nixos: Improve directory creation and permission and ownership assignment

---

nixos.nix

The logic for detecting whether a file or directory is specified multiple times was not updated to account for the recent file/filePath and directory/dirPath changes. This can lead to spurious failures like the following if the same home-relative path is persisted for different users:
Failed assertions:
- environment.persistence:
The following directories were specified two or more
times:
.cache
.config
.local/share
.local/state
.gnupg
.ssh
In addition, the assertion may falsely not trigger in the contrived situation where the same entity is persisted both in a per-user configuration (using the relative path) and the global configuration (using the absolute path).
Fix these situations by checking the absolute paths again using filePath and dirPath.

nixos: Fix collision detection logic

---

home-manager.nix

This fixes #105 by no longer generating an empty bash function. Empty functions in bash are invalid, which cause the activation to fail.

Skip generating bind mounts if no bind mounts are configured.

---

nixos.nix

The fstrim service, when enabled, by default trims all mounts listed in fstab (as long as the underlying device supports discard), including bind mounts. With impermanence, this can lead to a significant number of redundant trim operations, since the persistent volume is trimmed once for itself and then again once per persistent directory each. On my system, this leads to fstrim.service taking about 10 minutes, during which the system usability is somewhat degraded. In addition, it may be desired to disable trim for a certain filesystem entirely, for example when using btrfs with discard=async.
Mark our bind mounts with the X-fstrim.notrim option, which is ignored by mount, but instructs fstrim to skip the mount point in question. The persistent filesystem is still trimmed properly, since …

nixos: Prevent redundant fstrim

---

nixos.nix

This includes the options of all modules used in the evaluation, not just the ones from `<nixpkgs/nixos>` in the local manual.
Right now this breaks with
error: attribute '"‹name›"' missing
because the submodule `environment.persistence` doesn't have actual declarations when building the manual, but a dummy only to evaluate the sub-options (including their defaults which is the cause of the error) and generate documentation from that.
Using `defaultText` prevents that because there's no need anymore to evaluate the `default` values of the options.
cc @lovesegfault @talyz

Fix build with `documentation.nixos.includeAllModules = true;`

---

home-manager.nix

Add `persistentStoragePath` to the home-manager module, to be in line with #134 .
Would allow to do things such as...
```nix
home.persistence.main = {
persistentStoragePath = "/persistent";
files = [ ... ]
directories = [ ... ]
};
```
cc @talyz :)
EDIT: this is not tested yet. Trying to use it now.
EDIT2: I've been running this for months now, without any issues.
EDIT3: I do however have patched the following line, to always use symlink `getDirMethod = v: v.method or "bindfs";`

home-manager: add persistentStoragePath option

---

home-manager.nix
lib.nix
nixos.nix

`sanitizeName` is not necessary anymore and can be replaced by `utils.escapeSystemdPath`, which does a much better job anyway.
Fixes #132.

lib: Remove sanitizeName, replace usage with escapeSystemdPath

---

nixos.nix

Previously, we would always make some meaningless additions to `activationScripts` and such.
Also, remove some unused lib function imports from the module.
cc @0xf09f95b4

nixos: Disable module if no persistent storage paths are defined or all are disabled

---

nixos.nix

This is a good idea in itself.
Additionally, it avoids issues if users want to use mkDefault in their fileSystems config and have no persistent directories.

nixos: avoid side effects to fileSystems if possible

---

nixos.nix

nixos: Add assertion for persisting UIDs/GIDs

---

README.org

There was one to many "remove" in the sentence so I removed it.

removed obsolete word

---

nixos.nix

Previously, the user could have mounted a separate filesystem or subvolume on the path and we would show the warning unnecessarily.
Fixes #200.
cc @cdombroski @oluceps

nixos: Consider regular filesystem mounts in /var/lib/nixos warning

---

nixos.nix

Create directories which are persisted, but also happen to be marked as needed for boot, at early boot. This happens for a few paths which NixOS always marks as such if there's a `fileSystems`-entry for them, for example `/var/lib/nixos`.
Fixes #121.

nixos: Create persisted dirs marked as needed for boot before mount

---

nixos.nix

`mkIf` is already defined here.

nixos: Fix duplicate definition causing syntax error

---

create-directories.bash
nixos.nix

If they're not filesystem roots, they won't exist when deploying to a new system and would otherwise have to be manually created.
Fix #154
cc @tmarkov

nixos: Create persistent storage directories and their parents

---

mount-file.bash

Sometimes the root filesystem may not have been cleaned up or reset correctly, and this handles such situations more gracefully.

mount-file: allow file to exist if it's empty

---

home-manager.nix

This is possible in the nixos version and should be possible in home-manager too.

Allow disabling of persistant storage location in home-manager

---

create-directories.bash
mount-file.bash
nixos.nix

To make this work, we have to do two things:
`systemd-machine-id-commit` does its job just fine if the file contains `uninitialized`, even if it's bind mounted from persistent storage. It only misbehaves if the file contains an actual machine-id, since it then thinks it needs to be committed.
This can be worked around by only running the service on the first boot.
Our standard handling of non-existent files is to create a symlink, but this makes systemd behave a bit strangely. It follows the symlink and creates the `uninitialized` machine-id at the linked location. Then it bind mounts a newly generated machine-id over the file in persistent storage. This works, but it seems to confuse `systemd-machine-id-commit` since the file is not actually a bind mount over /etc/machine-id, so the …

Fix machine-id workaround to also work on first boot

---

nixos.nix

When generating the dependencies for the systemd unit, take into account the special cases where there not be any backing file system.
Fixes #237.
Fixos #239.

nixos: Improve handling of special file systems in create-needed-for-boot

---

home-manager.nix

Hi all!
Here's a (slightly late) follow up to https://github.com/nix-community/impermanence/pull/99.
This adds an option that allows users to change the default linking method.
Bindfs has been bothering me with the performance hits, and writing `method = symlink` for every entry is cumbersome. The default still is bindfs, so no breaking changes.
To make this implementation cleaner, I also refactored the directory type to use coercedTo (in its own commit, to be easier to review).

hm: option for default linking method
